title: <p align="center"> Giuseppe Pulino </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center"
  <a ></a> |
  <a href="https://www.linkedin.com/in/giuseppe-pulino-40a9981b2/">LinkedIn</a> |
  <a href="https://github.com/datascientist-hist">GitHub</a>|
  <a href="pdf/Resume.pdf">Resume</a> 
  </p>
  I am a Data Science student
  <br><br>
  Skills in:<br>
  
  <ul>
    <li>Python</li>
    <li>R</li>
    <li>Tableau</li>
    <li>MySQL</li>
  </ul>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
